---
title: "Thanos Shiny"
output: html_document
date: "2023-04-07"
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Framework

```{r}
library(shiny)
library(ggplot2)

# Define UI ----

# Shiny ideas from https://github.com/santiagosnchez/genetic_drift
ui <- fluidPage(
    titlePanel("Genetic Drift Simulator"),
    sidebarLayout(
        sidebarPanel(
            numericInput(
                inputId = "population_size", 
                label = "Population Size", 
                value = 100, 
                step = 1), 
                step = 1, 
                min = 2,
                max = 500
            ), 
            numericInput(
                inputId = "num_generations",
                label = "Number of Generations",
                value = 1,
                step = 1,
                min = 1,
                max = 20
            ),

            sliderInput(
                inputId = "initial_frequency", 
                label = "Initial Allele Frequency", 
                min = 0, 
                max = 1, 
                step = 0.05, 
                value = 0.50), 
            actionButton(
                inputId = "run", 
                label = "Run"), 
            actionButton(
                inputId = "reset", 
                label = "Reset"), 
            actionButton(
                inputId = "bottleneck", 
                label = "Bottleneck!")
            ),
        mainPanel(
            fluidRow(
                column(
                    4, 
                    verbatimTextOutput("Plots")
                    )
                ),
            fluidRow(
                column(
                    8, 
                    plotOutput("freq_plot")
                    )
                )
            )
        )


# Define server logic ----
server <- function(input, output) {
    output$population_size = renderText({
        input$population_size
    })
    
    output$num_generations = renderText({
        input$num_generations
    })
    
    output$initial_frequency = renderText({
        input$initial_frequency
    })
    
    observeEvent(input$run, {
        # Start simulation
      source("~/Desktop/Stat 345/Projects/345 Final Project Thanos Snap/FinalFunctions.R")
      simulate.generations(
        gens = input$num_generations, 
        start.freq = , 
        pop.size = input$population_size, 
        bottle = input$bottleneck, 
        surv.rate = )
    })
    
    observeEvent(input$reset, {
        # Stop simulation and clear progress
    })
    
    observeEvent(input$bottleneck, {
        # Use bottleneck function we create.
    })
}

# Run the app ----
shinyApp(ui = ui, server = server)



```




